.PHONY: run
run:
	@python3 main.py

# NOTE: 以下を実行しても仮想環境は有効化されない。なぜなら仮想環境はセッションごとに有効化する必要があるが、make targetの各行はそれぞれ別のシェルで実行されるため。
# .PHONY: activate
# activate:
# 	@bash -c "source lecture6/bin/activate"
